var docs = {
  'grid-area': {
    'en': '<p>Specifies a grid item\'s position and size within the grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'hi': '<p>????? ?? ???? ????? ???? ?? ?????? ?? ???? ????????? ???? ???</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'lv': '<p>Norada "grid" elementa/u poziciju un izmeru tava "grid".</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ro': '<p>Specifica pozi?ia ?i marimea unui element al gridului în grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'fr': '<p>Définit la position et la taille d\'un élément dans la grille.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'de': '<p>Bestimmt die Position und Grösse eines Elements im Raster.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'nl': '<p>Bepaalt de positie en grootte van een item in het grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'pt-br': '<p>Especifica a posição e o tamanho do item dentro da grade.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'zh-cn': '<p>??????????????????</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'zh-tw': '<p>??????????????????</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanin konumunu ve grid içerisindeki boyutunu belirler.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'az': '<p>Grid\'d?ki bir hiss?nin mövqeyini v? gridin içind?ki ölçüsünü t?yin ed?r.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ru': '<p>?????????? ??????? ? ?????? grid-???????? ?????? grid-?????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'pl': '<p>Definiuje pozycje i wielkosc elementu grid wewnatrz siatki grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'es': '<p>Define la posición y el tamaño de un elemento en la cuadrícula.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements position och storlek inuti rutnätet.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'fa': '<p>?????? ? ?????? ?? ???? ???? ?? ?? ???? ???? ?? ???.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'it': '<p>Specifica la posizione e la dimensione di un elemento nella griglia.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ko': '<p>??? ??? ??? ??? ?????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'el': '<p>???sd?????e? t?? ??s? ?a? µ??e??? e??? a?t??e?µ???? t?? p???µat?? µ?sa st? p???µa.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ja': '<p>????????????????????????????</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ua': '<p>???????? ??????? ? ?????? grid ???????? ????????? grid ?????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'no': '<p>Spesifiserer posisjonen til gridelementet og dets størrelse på rutenettet.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição e o tamanho de um elemento na grelha.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'bg': '<p>???????? ????????? ? ??????? ?? grid-???????? ? ?????????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'he': '<p>???? ?? ????? ??? ????? ?? grid-item ???? ?????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ca': '<p>Defineix la posició i la mida d\'un element a la quadrícula.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'vi': '<p>Xác d?nh v? trí và kích thu?c c?a m?t d?i tu?ng bên trong grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ar' : '<p> ???? ??????  ?????? ????? ???? </p> <p dir="ltr"><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p> ',
    'fi': '<p>Määrittää elementin sijainnin ja koon ruudukossa.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem pozícióját és méretét.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'id': '<p>Menentukan letak dan ukuran item grid di dalam grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa position ng grid item at and size nito sa loob ng grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'al': '<p>Specifikon pozicionin dhe madhësinë e një grid item brenda në grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'et': '<p>Määrab ruudustiku üksuse asukoha ja suuruse ruudustikus.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'th': '<p>?????????????????? grid item ???????????? grid</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'yo': '<p>S? ní pàtó ipò grid item\'s àti ìw?`n r?` láàrín grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'sk': '<p>Urcuje polohu a velkost prvku mriežky v rámci mriežky.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
    'ta': '<p>?????????????? ?????? ???????????? ???? ??????? ?????? ???????????????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-column-start&gt; / &lt;grid-row-end&gt; / &lt;grid-column-end&gt;</code></p>',
  },
  'grid-column': {
    'en': '<p>Specifies a grid item\'s position within the grid columns.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'lv': '<p>Norada "grid" elementa/u poziciju tava "grid" kolonna.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ro': '<p>Specifica pozi?ia unui element al gridului în coloanele gridului.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'fr': '<p>Définit la position d\'un élément de la grille sur les colonnes de la grille.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'zh-cn': '<p>????????????????</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code>',
    'zh-tw': '<p>????????????????</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code>',
    'tr': '<p>Grid\'teki bir parçanin grid kolonundaki pozisyonunu belirler. </p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'az': '<p>Grid\'d?ki bir hiss?nin grid sütunundaki mövqeyini t?yin ed?r. </p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'de': '<p>Bestimmt die Position eines Elements innerhalb der Spalten des Rasters.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'nl': '<p>Bepaalt de positie van een item binnen de kolommen van het grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'pt-br': '<p>Especifica a posição do item de acordo com as colunas da grade.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ru': '<p>?????????? ??????? grid-???????? ?????? grid-????????.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'pl': '<p>Definiuje pozycje elementu grid w kolumnie grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'es': '<p>Define la posición de un elemento respecto a las columnas de la cuadrícula.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements position inuti rutnätets kolumner.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'fa': '<p>?????? ???? ???? ?? ?? ???? ???? ?? ???? ?? ???.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'it': '<p>Specifica la posizione di un elemente rispetto alle colonne della griglia.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ko': '<p>??? ??? ?(column) ??? ?????.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'el': '<p>???sd?????e? t?? ??s? e??? a?t??e?µ???? t?? p???µat?? µ?sa st?? st??e? t?? p???µat??.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ja': '<p>????????????????????</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ua': '<p>???????? ??????? grid ???????? ????????? grid ????????.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'no': '<p>Spesifiserer posisjonen til gridelementet i kolonnene på rutenettet.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição de um elemento em respeito às colunas da grelha.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'bg': '<p>???????? ????????? ?? grid-???????? ? ???????? ?? ?????????.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'he': '<p>???? ?? ????? ?? ?grid-item ???? ?????? ?????.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ca': '<p>Defineix la posició d\'un element respecte les columnes de la quadrícula.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'vi': '<p>Xác d?nh v? trí c?a m?t d?i tu?ng bên trong grid theo c?t.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ar': '<p> ???? ?????? ?????  ??? ????? ?????? </p> <p dir="ltr"> <code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code> </p> ',
    'fi': '<p>Määrittää elementin sijainnin ruudukon pystyriveillä.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem pozícióját a rács oszlopai közt.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'id': '<p>Menentukan letak item grid di dalam kolom grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa position ng grid item sa loob ng mga column ng grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'al': '<p>Specifikon pozicionin e një grid item brenda kolonave të gird.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'et': '<p>Määrab ruudustiku üksuse asukoha ruudustiku veergudes.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'th': '<p>?????????????????? grid item ????? grid columns</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'yo': '<p>S? ní pàtó ipò àw?n nkan grid nínú àw?n ìlà grid.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'sk': '<p>Urcuje polohu prvku mriežky v rámci stlpcov mriežky.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'ta': '<p>?????? ????????????? ???? ???????????? ???????? ?????????????.</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
  },
  'grid-column-end': {
    'en': '<p>Specifies a grid item\'s end position within the grid columns.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'hi': '<p>????? ???? ??? ????? ???? ?? ?????? ????????? ???? ???</p><p><code>&lt;grid-column-start&gt; / &lt;grid-column-end&gt;</code></p>',
    'lv': '<p>Norada "grid" elementa/u beigu poziciju tavas "grid" kolonnas.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ro': '<p>Specifica pozi?ia de sfâr?it a unui element al gridului în coloanele gridului.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fr': '<p>Définit la position de fin d\'un élément de la grille sur les colonnes de la grille.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-cn': '<p>??????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-tw': '<p>??????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanin grid kolonundaki son pozisyonunu belirler.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'az': '<p>Grid\'d?ki bir hiss?nin grid sütunundaki sonuncu mövqeyini t?yin ed?r.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Endposition eines Elements innerhalb der Spalten des Rasters.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de eindpositie van een item binnen de gridkolommen.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a posição final do item de acordo com as colunas da grade.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ru': '<p>?????????? ???????? ??????? grid-???????? ?????? grid-????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pl': '<p>Definuje pozycje koncowa elementu grid w kolumnie grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'es': '<p>Define la posición final de un elemento respecto a las columnas de la cuadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements slutposition inuti rutnätets kolumner.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fa': '<p>???? ????? ???? ???? ?? ?? ???? ???? ?? ???? ?? ???.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'it': '<p>Specifica la posizione finale di un elemento rispetto alle colonne della griglia.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ko': '<p>??? ??? ??? ?(column) ??? ?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'el': '<p>???sd?????e? t?? te???? ??s? e??? a?t??e?µ???? t?? p???µat?? µ?sa st?? st??e? t?? p???µat??.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ja': '<p>??????????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ua': '<p>???????? ??????? ??????? grid ???????? ????????? grid ????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer sluttposisjonen til gridelementet i kolonnene på rutenettet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição final de um elemento em respeito às colunas da grelha.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'bg': '<p>???????? ???????? ??????? ?? grid-???????? ? ???????? ?? ?????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'he': '<p>???? ?? ?????? ????? ?? grid-item.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ca': '<p>Defineix la posició final d\'un element respecte les columnes de la quadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'vi': '<p>Xác d?nh v? trí k?t thúc c?a m?t d?i tu?ng bên trong grid theo c?t.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ar': '<p> ???? ???? ????? ???? ??? ????? ????? </p> <p dir="ltr"> <code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code> </p>',
    'fi': '<p>Määrittää elementin lopetuskohdan ruudukon pystyriveillä.</p><p><code>&lt;kokonaisluku&gt;</code> <code>span &lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem vég pozícióját a rács oszlopai közt.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'id': '<p>Menentukan letak akhir item grid di dalam kolom grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa end position ng grid item sa loob ng mga column ng grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'al': '<p>Specifikon pozicionin ne fund të një grid item brenda kolonave të grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'et': '<p>Määrab ruudustiku üksuse lõppasendi ruudustiku veergudes.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'th': '<p>????????????????????????? grid item ????? grid columns</p><p><code>&lt;????????????&gt;</code> <code>span &lt;????????????&gt;</code></p>',
    'yo': '<p>S? ní pàtó ipò òpin grid item\'s láàrin àw?n ìlà grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sk': '<p>Urcuje koncovú pozíciu prvku mriežky v rámci stlpcov mriežky.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ta': '<p>?????? ??????????? ??????? ?????? ???????????? ????? ???????? ?????????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
  },
  'grid-column-start': {
    'en': '<p>Specifies a grid item\'s start position within the grid columns.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'hi': '<p>????? ???? ??? ????? ???? ?? ??????? ?????? ????????? ???? ???</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'lv': '<p>Norada "grid" elementa/u sakuma poziciju tavas "grid" kolonnas.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ro': '<p>Specifica pozi?ia de început a unui element al gridului în coloanele gridului.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-cn': '<p>??????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-tw': '<p>??????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanin grid kolonundaki ilk pozisyonunu belirler.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'az': '<p>Grid\'d?ki bir hiss?nin grid sütunudaki ilk mövqeyini t?yin ed?r.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fr': '<p>Définit la position du début d\'un élément de la grille sur les colonnes de la grille.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Startposition innerhalb der Spalten des Rasters.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de startpositie binnen de gridkolommen.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a posição inicial do item de acordo com as colunas da grade.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ru': '<p>?????????? ????????? ??????? grid-???????? ?????? grid-????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pl': '<p>Definiuje pozycje poczatkowa elementu grid w kolumnie grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'es': '<p>Define la posición inicial de un elemento respecto a las columnas de la cuadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements startposition inuti rutnätet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fa': '<p>???? ???? ???? ???? ?? ?? ???? ???? ?? ???? ?? ???.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'it': '<p>Specifica la posizione iniziale di un elemento rispetto alle colonne della griglia.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ko': '<p>??? ??? ?? ?(column) ??? ?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'el': '<p>???sd?????e? t?? a????? ??s? e??? a?t??e?µ???? t?? p???µat?? µ?sa st?? st??e? t?? p???µat??.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ja': '<p>??????????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ua': '<p>???????? ????????? ??????? grid ???????? ????????? grid ????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer startposisjonen til gridelementet på rutenettet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição inicial de um elemento em respeito às colunas da grelha.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'bg': '<p>???????? ????????? ??????? ?? grid-???????? ? ???????? ?? ?????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'he': '<p>???? ?? ?????? ??????? ?? ?grid-item ???? ?????? ?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ca': '<p>Defineix la posició inicial d\'un element respecte les columnes de la quadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'vi': '<p>Xác d?nh v? trí b?t d?u c?a m?t d?i tu?ng bên trong grid theo c?t.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ar': '<p> ???? ???? ????? ???? ??? ????? ????? </p> <p dir="ltr"> <code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code> </p>',
    'fi': '<p>Määrittää elementin aloituskohdan ruudukon pystyriveillä.</p><p><code>&lt;kokonaisluku&gt;</code> <code>span &lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem kezdo pozícióját a rács oszlopai közt.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'id': '<p>Menentukan letak awal item grid di dalam kolom grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa start position ng grid item sa loob ng mga column ng grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'al': '<p>Specifikon pozicionin në fillim të një grid item brenda kolonave te grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'et': '<p>Määrab ruudustiku üksuse alguspositsiooni ruudustiku veergudes.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'th': '<p>??????????????????????????  grid item ????? grid columns</p><p><code>&lt;????????????&gt;</code> <code>span &lt;????????????&gt;</code></p>',
    'yo': '<p>S? ní pàtó ipò ìb?`r?` grid item\'s láàrin àw?n ìlà grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sk': '<p>Urcuje pociatocnú pozíciu prvku mriežky v rámci stlpcov mriežky.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ta': '<p>?????? ??????????? ??????? ?????? ???????????? ?????? ???????? ?????????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
  },
  'grid-row': {
    'en': '<p>Specifies a grid item\'s position within the grid rows.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'hi': '<p>????? ????????? ??? ????? ???? ?? ?????? ????????? ???? ???</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'lv': '<p>Norada "grid" elementa/u poziciju tavas "grid" rindas.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ro': '<p>Specifica pozi?ia unui element al gridului în rândurile gridului.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'zh-cn': '<p>????????????????</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'zh-tw': '<p>????????????????</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanin grid satirindaki pozisyonunu belirler.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'az': '<p>Grid\'d?ki bir hiss?nin grid s?tirind?ki mövqeyini t?yin ed?r.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'fr': '<p>Définit la position d\'un élément de la grille sur les lignes de la grille.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'de': '<p>Bestimmt die Position eines Elements innerhalb der Reihen des Rasters.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'nl': '<p>Bepaalt de positie van een item binnen de gridrijen.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'pt-br': '<p>Especifica a posição do item de acordo com as linhas da grade.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ru': '<p>?????????? ??????? grid-???????? ?????? grid-?????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'pl': '<p>Definiuje pozycje elementu grid w wierszu grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'es': '<p>Define la posición de un elemento respecto a las filas de la cuadrícula.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements position inuti rutnätets rader.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'fa': '<p>?????? ???? ???? ?? ?? ??? ???? ?? ???? ?? ???.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'it': '<p>Specifica la posizione di un elemente rispetto alle righe della griglia.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ko': '<p>??? ??? ?(row) ??? ?????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'el': '<p>???sd?????e? t?? ??s? e??? a?t??e?µ???? t?? p???µat?? µ?sa st?? se???? t?? p???µat??.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ja': '<p>????????????????????</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ua': '<p>???????? ??????? grid ???????? ????????? grid ??????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'no': '<p>Spesifiserer posisjonen til gridelementet i radene på rutenettet.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição de um elemento em respeito às linhas da grelha.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'bg': '<p>???????? ????????? ?? grid-???????? ? ???????? ?? ?????????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'he': '<p>???? ?? ????? ?? grid-item ???? ????? ?????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ca': '<p>Defineix la posició d\'un element respecte les files de la quadrícula.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'vi': '<p>Xác d?nh v? trí c?a m?t d?i tu?ng bên trong grid theo hàng.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ar': '<p> ???? ???? ?????? ?? ???? ???? ?????? </p><p dir="ltr"><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'fi': '<p>Määrittää elementin sijainnin ruudukon vaakariveillä.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem pozícióját a rács sorai közt.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'id': '<p>Menentukan letak item grid di dalam baris grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa position ng grid item sa loob ng mga row ng grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'al': '<p>Specifikon pozicionin brenda rrjeshtave të grid të një grid item.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'et': '<p>Määrab ruudustiku üksuse asukoha ruudustiku ridades.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'th': '<p>?????????????????? grid item ????? grid rows</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'yo': '<p>S? ní pàtó ipò grid item\'s láàrin àw?n ìlà grid.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'sk': '<p>Urcuje polohu prvku mriežky v rámci riadkov mriežky.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
    'ta': '<p>?????? ??????????? ??????? ?????? ???????????? ???????? ?????????????.</p><p><code>&lt;grid-row-start&gt; / &lt;grid-row-end&gt;</code></p>',
  },
  'grid-row-end': {
    'en': '<p>Specifies a grid item\'s end position within the grid rows.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'hi': '<p>????? ????????? ?? ???? ????? ???? ?? ????? ?????? ????????? ???? ???</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'lv': '<p>Norada "grid elementa/u beigu poziciju tavas "grid" rindas.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ro': '<p>Specifica pozi?ia de sfâr?it a unui element al gridului în rândurile gridului./p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-cn': '<p>??????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-tw': '<p>??????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanin grid satirindaki son pozisyonunu belirler.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'az': '<p>Grid\'d?ki bir hiss?nin grid s?tirind?ki son mövqeyini t?yin ed?r.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fr': '<p>Définit la position de fin d\'un élément de la grille sur les lignes de la grille.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Endposition innerhalb der Reihen des Rasters.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de eindpositie binnen de gridrijen.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a posição final do item de acordo com as linhas da grade.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ru': '<p>?????????? ???????? ??????? grid-???????? ?????? grid-?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pl': '<p>Definiuje pozycje koncowa w wierszu grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'es': '<p>Define la posición final de un elemento respecto a las filas de la cuadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements slutposition inuti rutnätets rader.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fa': '<p>???? ????? ???? ???? ?? ?? ??? ???? ?? ???? ?? ???.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'it': '<p>Specifica la posizione finale di un elemento rispetto alle righe della griglia.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ko': '<p>??? ??? ??? ?(row) ??? ?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'el': '<p>???sd?????e? t?? te???? ??s? e??? a?t??e?µ???? t?? p???µat?? µ?sa st?? se???? t?? p???µat??.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ja': '<p>??????????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ua': '<p>???????? ??????? ??????? grid ???????? ????????? grid ??????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer sluttposisjonen til gridelementet i radene på rutenettet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição final de um elemento em respeito às linhas da grelha.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'bg': '<p>???????? ???????? ??????? ?? grid-???????? ? ???????? ?? ?????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'he': '<p>???? ?? ?????? ????? ?? grid-item ???? ????? ?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ca': '<p>Defineix la posició final d\'un element respecte les files de la quadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'vi': '<p>Xác d?nh v? trí k?t thúc c?a m?t d?i tu?ng bên trong grid theo hàng.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ar': '<p> ???? ???? ????? ???? ??? ???? ????? </p> <p dir="ltr"> <code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code> </p>',
    'fi': '<p>Määrittää elementin lopetuskohdan ruudukon vaakariveillä.</p><p><code>&lt;kokonaisluku&gt;</code> <code>span &lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem vég pozícióját a rács sorai közt.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'id': '<p>Menentukan letak akhir item grid di dalam baris grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa end position ng grid item sa loob ng mga row ng grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'al': '<p>Specifikon pozicionin në fund brenda rrjeshtave të grid të një grid item.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'et': '<p>Määrab ruudustiku üksuse lõppasendi ruudustiku ridades.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'th': '<p>????????????????????????? grid item ????? grid rows</p><p><code>&lt;????????????&gt;</code> <code>span &lt;????????????&gt;</code></p>',
    'yo': '<p>S? ní pàtó ipò grid item\'s láàrin àw?n ìlà grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sk': '<p>Urcuje koncovú pozíciu prvku mriežky v rámci riadkov mriežky.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ta': '<p>?????? ??????????? ??????? ?????? ???????????? ???????? ?????????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
  },
  'grid-row-start': {
    'en': '<p>Specifies a grid item\'s start position within the grid rows.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'hi': '<p>????? ????????? ?? ???? ????? ???? ?? ??????? ?????? ????????? ???? ???</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'lv': '<p>Norada "grid" elemanta/u sakuma poziciju tavas "grid" rindas.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ro': '<p>Specifica pozi?ia de început a unui element al gridului în rândurile gridului.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-cn': '<p>??????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'zh-tw': '<p>??????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanin grid satirindaki ilk pozisyonunu belirler.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'az': '<p>Grid\'d?ki bir hiss?nin grid s?tirind?ki ilk mövqeyini t?yin ed?r.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fr': '<p>Définit la position du début d\'un élément de la grille sur les lignes de la grille.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Startposition innerhalb der Reihen des Rasters.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de startpositie binnen de gridrijen.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a posição inicial do item de acordo com as linhas da grade.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ru': '<p>?????????? ????????? ??????? grid-???????? ?????? grid-?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pl': '<p>Definiuje pozycje poczatkowa elementu grid w wierszu grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'es': '<p>Define la posición inicial de un elemento respecto a las filas de la cuadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett gridelements startposition inuti rutnätets rader.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'fa': '<p>???? ???? ???? ???? ?? ?? ??? ???? ?? ???? ?? ???.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'it': '<p>Specifica la posizione iniziale di un elemento rispetto alle righe della griglia.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ko': '<p>??? ??? ?? ?(row) ??? ?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'el': '<p>???sd?????e? t?? a????? ??s? e??? a?t??e?µ???? t?? p???µat?? µ?sa st?? se???? t?? p???µat??.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ja': '<p>??????????????????????</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ua': '<p>???????? ????????? ??????? grid ???????? ????????? grid ??????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer startposisjonen til gridelementet i radene på rutenettet.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a posição inicial de um elemento em respeito às linhas da grelha.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'bg': '<p>???????? ????????? ??????? ?? grid-???????? ? ???????? ?? ?????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'he': '<p>???? ?? ?????? ??????? ?? grid-item ???? ????? ?????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ca': '<p>Defineix la posició inicial d\'un element respecte les files de la quadrícula.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'vi': '<p>Xác d?nh v? trí b?t d?u c?a m?t d?i tu?ng bên trong grid theo hàng.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ar': '<p> ???? ???? ????? ???? ??? ???? ????? </p> <p dir="ltr"> <code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code> </p>',
    'fi': '<p>Määrittää elementin aloituskohdan ruudukon vaakariveillä.</p><p><code>&lt;kokonaisluku&gt;</code> <code>span &lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza egy rácselem kezdo pozícióját a rács sorai közt.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'id': '<p>Menentukan letak awal item grid di dalam baris grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa start position ng grid item sa loob ng mga row ng grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'al': '<p>Specifikon pozicionin fillestar të një gird item brenda rrjeshatve të grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'et': '<p>Määrab ruudustiku üksuse alguskoha ruudustiku ridades.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'th': '<p>?????????????????????????? grid item ????? grid rows</p><p><code>&lt;????????????&gt;</code> <code>span &lt;????????????&gt;</code></p>',
    'yo': '<p>S? ní pàtó ipò ìb?`r?` grid item\'s láàrin àw?n ìlà grid.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'sk': '<p>Urcuje pociatocnú pozíciu prvku mriežky v rámci riadkov mriežky.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
    'ta': '<p>?????? ??????????? ??????? ?????? ???????????? ?????? ???????? ?????????????.</p><p><code>&lt;integer&gt;</code> <code>span &lt;integer&gt;</code></p>',
  },
  'grid-template': {
    'en': '<p>Specifies the sizing and names of the grid\'s rows and columns.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'hi': '<p>????? ?? ????????? ?? ??????? ?? ???? ?? ??? ????????? ???? ???</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'lv': '<p>Norada "grid" rindu un kolonnu izmerus un nosaukumus.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ro': '<p>Specifica marimea ?i numele rândurilor ?i coloanelor gridului.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'fr': '<p>Définit le dimensionnement et les noms des lignes et des colonnes de la grille.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'zh-cn': '<p>????????????????</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'zh-tw': '<p>????????????????</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'tr': '<p>Grid\'in satir ve kolonlarinin isimlerini ve ölçülerini belirler.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'az': '<p>Grid\'in s?tir v? sütunlarinin adlarini v? ölçül?rini t?yin ed?r.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'de': '<p>Bestimmt die Abmessungen und Namen der Reihen und Spalten des Rasters.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'nl': '<p>Bepaalt de afmetingen en namen van de gridrijen en -kolommen.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'pt-br': '<p>Especifica o tamanho das linhas e colunas da grade.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ru': '<p>?????????? ?????? ? ???????? ??? grid-????? ? ????????.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'pl': '<p>Definiuje wielkosc i nazwy wierszy i kolumn grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'es': '<p>Define el tamaño y nombres de las filas y las columnas de la cuadrícula.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'sv': '<p>Specifierar storlek och namn för rutnätets rader och kolumner.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'fa': '<p>?????? ? ??? ????? ? ???? ??? ???? ?? ???? ?? ???.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'it': '<p>Specifica la dimensione e i nomi delle righe e delle colonne della griglia.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ko': '<p>???? ?(row)? ?(column)? ?? ??? ??? ?????.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'el': '<p>???sd?????e? t? µ??e??? ?a? ta ???µata t?? se???? ?a? st???? t?? p???µat??.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ja': '<p>??????????????????????</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ua': '<p>???????? ?????? ? ????? ??? grid ?????? ? ????????.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'no': '<p>Spesifiserer størrelsene og navnene på radene og kolonnene til rutenettet.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'pt-pt': '<p>Especifica as dimensões e nomes das linhas e colunas da grelha.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'bg': '<p>???????? ??????? ? ??????? ?? ???????? ? ???????? ?? ?????????.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'he': '<p>???? ?? ????? ?????? ?? ?????? ???????? ?? ?????.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ca': '<p>Defineix la mida i els noms de les files i columnes de la quadrícula.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'vi': '<p>Xác d?nh kích thu?c và tên các c?t, hàng bên trong grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ar': '<p> ???? ????? ?????? ???? ????? ??????</p><p dir="ltr"><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'fi': '<p>Määrittää ruudukon vaaka- ja pystyrivien koot ja nimet.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'hu': '<p>Meghatározza a rács oszlopainak és sorainak méretét és elnevezésüket.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'id': '<p>Menentukan ukuran dan nama dari baris dan kolom grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa sukat at pangalan ng rows at columns ng grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'al': '<p>Specifikon madhësitë dhe emrat e rrjeshtave dhe kolonave të grid.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'et': '<p>Määrab ruudustiku ridade ja veergude suuruse ja nimed.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'th': '<p>?????????????????????? grid rows ??? columns</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'yo': '<p>S? ní pàtó awon afihan aw?n iw?n ati aw?n oruk? ti aw?n ila grid\'s ati aw?n ?w?n.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'sk': '<p>Urcuje velkost a názvy riadkov a stlpcov mriežky.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
    'ta': '<p>?????????? ???????? ??????? ?????????????? ?????? ??????? ??????? ?????????? ?????????????.</p><p><code>&lt;grid-template-rows&gt; / &lt;grid-template-columns&gt;</code></p>',
  },
  'grid-template-areas': {
    'en': '<p>Specifies named grid areas.</p><p><code>&lt;grid-name&gt;</code></p>',
    'hi': '<p>????? ????? ????????? ?? ????????? ???? ???</p><p><code>&lt;grid-name&gt;</code></p>',
    'lv': '<p>Norada "grid" zonu nosaukumus.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ro': '<p>Specifica zonele numite ale gridului.</p><p><code>&lt;grid-name&gt;</code></p>',
    'zh-cn': '<p>???????????</p><p><code>&lt;grid-name&gt;</code></p>',
    'zh-tw': '<p>???????????</p><p><code>&lt;grid-name&gt;</code></p>',
    'tr': '<p>Isimlendirilmis grid alanlarini belirler.</p><p><code>&lt;grid-name&gt;</code></p>',
    'az': '<p>Adlandirilmis grid sah?l?rini t?yin ed?r.</p><p><code>&lt;grid-name&gt;</code></p>',
    'fr': '<p>Définit les régions de grille nommées</p><p><code>&lt;grid-name&gt;</code></p>',
    'de': '<p>Bestimmt benannte Rasterbereiche.</p><p><code>&lt;grid-name&gt;</code></p>',
    'nl': '<p>Bepaalt de benoemde gridgebieden.</p><p><code>&lt;grid-name&gt;</code></p>',
    'pt-br': '<p>Especifica as áreas da grade.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ru': '<p>?????????? ????????? grid-????.</p><p><code>&lt;grid-name&gt;</code></p>',
    'pl': '<p>Definiuje nazwy powierzchni grid.</p><p><code>&lt;grid-name&gt;</code></p>',
    'es': '<p>Define las áreas de la cuadrícula nombradas.</p><p><code>&lt;grid-name&gt;</code></p>',
    'sv': '<p>Specifierar namngivna grid områden.</p><p><code>&lt;grid-name&gt;</code></p>',
    'fa': '<p>????? ??? ???? ?? ???? ?? ???.</p><p><code>&lt;grid-name&gt;</code></p>',
    'it': '<p>Specifica le aree denominate della griglia.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ko': '<p>??? ???? ??? ?????.</p><p><code>&lt;grid-name&gt;</code></p>',
    'el': '<p>???sd?????e? ?at???µasµ??e? pe?????? t?? p???µat??.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ja': '<p>??????????????</p><p><code>&lt;grid-name&gt;</code></p>',
    'ua': '<p>???????? ??????? grid ????.</p><p><code>&lt;grid-name&gt;</code></p>',
    'no': '<p>Spesifiserer navngitte områder på rutenettet.</p><p><code>&lt;grid-name&gt;</code></p>',
    'pt-pt': '<p>Especifica as áreas nomeadas da grelha.</p><p><code>&lt;grid-name&gt;</code></p>',
    'bg': '<p>???????? ????????????? ???? ?? ?????????.</p><p><code>&lt;grid-name&gt;</code></p>',
    'he': '<p>???? ?? ????? ????? ??????.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ca': '<p>Defineix les àrees de la quadrícula anomenades.</p><p><code>&lt;grid-name&gt;</code></p>',
    'vi': '<p>Xác d?nh vùng grid du?c d?t tên.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ar': '<p>???? ????? ?????? ???????</p><p dir="ltr"><code>&lt;grid-name&gt;</code></p>',
    'fi': '<p>Määrittää nimetyt ruudukkoalueet.</p><p><code>&lt;ruudukon-nimi&gt;</code></p>',
    'hu': '<p>Meghatározza egy elnevezett rács területet.</p><p><code>&lt;grid-name&gt;</code></p>',
    'id': '<p>Menentukan area dari grid yang telah diberi nama.</p><p><code>&lt;grid-name&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa mga nilagyan ng name na grid area.</p><p><code>&lt;grid-name&gt;</code></p>',
    'al': '<p>Specifikon zonat e emëruara të grid.</p><p><code>&lt;grid-name&gt;</code></p>',
    'et': '<p>Määrab nimetatud ruudustiku alad.</p><p><code>&lt;grid-name&gt;</code></p>',
    'th': '<p>??????????????? grid areas</p><p><code>&lt;grid-name&gt;</code></p>',
    'yo': '</p>S? ní pàtó àw?n agbègbè grid.<p><code>&lt;grid-name&gt;</code></p>',
    'sk': '<p>Urcuje pomenované oblasti mriežky.</p><p><code>&lt;grid-name&gt;</code></p>',
    'ta': '</p>?????? ?????????? ?????????????.<p><code>&lt;grid-name&gt;</code></p>',
  },
  'grid-template-columns': {
    'en': '<p>Specifies the sizing and names of the grid\'s columns.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'hi': '<p>????? ?? ???? ?? ???? ?? ??? ????????? ???? ???</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'lv': '<p>Norada "grid" kolonnu nosaukumus un izmerus.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ro': '<p>Specifica marimea ?i numele coloanelor gridului.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fr': '<p>Définit le dimensionnement et les noms des colonnes de la grille.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'zh-cn': '<p>?????????????</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'zh-tw': '<p>?????????????</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'tr': '<p>Grid kolonlarinin isimlerini ve ölçülerini belirler.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'az': '<p>Grid sütunlarinin adlarini v? ölçül?rini t?yin ed?r.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'de': '<p>Bestimmt die Abmessungen und Namen der Spalten des Rasters.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'nl': '<p>Bepaalt de afmetingen en namen van de gridkolommen.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pt-br': '<p>Especifica o tamanho das colunas da grade.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ru': '<p>?????????? ?????? ? ???????? ??? grid-????????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pl': '<p>Definiuje wielkosc i nazwy kolumn grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'es': '<p>Especifica el tamaño y los nombres de las columnas de la cuadrícula.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'sv': '<p>Specifierar storlek och namn för rutnätets kolumner.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fa': '<p>?????? ? ??? ???? ??? ???? ?? ???? ?? ???.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'it': '<p>Specifica la dimensione e i nomi delle colonne della griglia.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ko': '<p>???? ?(column) ??? ??? ?????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'el': '<p>???sd?????e? t? µ??e??? ?a? ta ???µata t?? st???? t?? p???µat??.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ja': '<p>????????????????????</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ua': '<p>???????? ?????? ? ????? ??? grid ????????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'no': '<p>Spesifiserer størrelsene og navnene på kolonnene til rutenettet.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pt-pt': '<p>Especifica as dimensões e nomes das colunas da grelha.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'bg': '<p>???????? ??????? ? ??????? ?? ???????? ?? ?????????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'he': '<p>???? ?? ?????? ??? ????? ?? ?????? ?????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ca': '<p>Especifica la mida i els noms de les columnes de la quadrícula.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'vi': '<p>Xác d?nh kích thu?c và tên các c?t bên trong grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ar': '<p>???? ???????? ???????? ?????? ?????? </p><p dir="ltr"><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fi': '<p>Määrittää ruudukon pystyrivien koot ja nimet.</p><p><code>&lt;pituusyksikkö&gt;</code> <code>&lt;prosenttiarvo&gt;</code> <code>&lt;fr-yksikkö&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'hu': '<p>Meghatározza a rács oszlopainak méretét és nevét.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'id': '<p>Menentukan ukuran dan nama kolom dari grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'tl': '<p>Tumutukoy ito sa sukat at pangalan ng columns ng grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'al': '<p>Specifikon madhesitë dhe emrat e kolonave të grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'et': '<p>Määrab ruudustiku veergude suuruse ja nimed.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'th': '<p>?????????????????????? grid columns</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'yo': '<p>S? ní pàtó ìw?`n àti orúk? àw?n ?`w?`n grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'sk': '<p>Urcuje velkost a názvy stlpcov mriežky.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ta': '<p>???? ?????????????? ???? ??????? ??????? ?????????????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
  },
  'grid-template-rows': {
    'en': '<p>Specifies the sizing and names of the grid\'s rows.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'hi': '<p>????? ?? ????????? ?? ???? ?? ??? ????????? ???? ???</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'lv': '<p>Norada "grid" rindu nosaukumus un izmerus.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ro': '<p>Specifica marimea ?i numele rândurilor gridului.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'zh-cn': '<p>?????????????</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'zh-tw': '<p>?????????????</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'tr': '<p>Grid satirlarinin isimlerini ve ölçülerini belirler.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'az': '<p>Grid s?tirl?rinin adlarini v? ölçül?rini t?yin ed?r.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fr': '<p>Définit le dimensionnement et les noms des lignes de la grille.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'de': '<p>Bestimmt die Abmessungen und Namen der Reihen des Rasters.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'nl': '<p>Bepaalt de afmetingen en namen van de gridrijen.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pt-br': '<p>Especifica o tamanho das linhas da grade.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ru': '<p>?????????? ?????? ? ???????? ??? grid-?????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pl': '<p>Definiuje wielkosc i nazwy wierszy grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'es': '<p>Define el tamaño y los nombres de las filas de la cuadrícula.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'sv': '<p>Specifierar storlek och namn för rutnätets rader.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fa': '<p>?????? ? ??? ?????? ???? ?? ???? ?? ???.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'it': '<p>Specifica la dimensione e i nomi delle righe della griglia.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ko': '<p>???? ?(row) ??? ??? ?????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'el': '<p>???sd?????e? t? µ??e??? ?a? ta ???µata t?? se???? t?? p???µat??.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ja': '<p>????????????????????</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ua': '<p>???????? ?????? ? ????? ??? grid ??????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'no': '<p>Spesifiserer størrelsene og navnene på radene til rutenettet.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'pt-pt': '<p>Especifica as dimensões e nomes das linhas da grelha.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'bg': '<p>???????? ??????? ? ??????? ?? ???????? ?? ?????????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'he': '<p>???? ?? ?????? ?????? ?? ????? ?????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ca': '<p>Defineix la mida i els noms de les files de la quadrícula.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'vi': '<p>Xác d?nh kích thu?c và tên các hàng bên trong grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ar': '<p>???? ???????? ???????? ????? ?????? </p><p dir="ltr"><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'fi': '<p>Määrittää ruudukon vaakarivien koon ja nimet.</p><p><code>&lt;pituusyksikkö&gt;</code> <code>&lt;prosenttiarvo&gt;</code> <code>&lt;fr-yksikkö&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'hu': '<p>Meghatározza a rács sorainak méretét és nevét.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'id': '<p>Menentukan ukuran dan nama baris dari grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'tl': '<p>Tumutukoy ito sa sukat at pangalan ng rows ng grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'al': '<p>Specifikon madhesitë dhe emrat e rrjeshtave të grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'et': '<p>Määrab ruudustiku ridade suuruse ja nimed.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'th': '<p>?????????????????????? grid rows</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'yo': '<p>S? ní pàtó aw?n ìw?`n ati aw?n oruk? ti aw?n ila grid.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'sk': '<p>Urcuje velkost a názvy riadkov mriežky.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
    'ta': '<p>?????? ????????? ??????? ??????? ?????????? ?????????????.</p><p><code>&lt;length&gt;</code> <code>&lt;percentage&gt;</code> <code>&lt;flex&gt;</code> <code>max-content</code> <code>min-content</code> <code>minmax(min, max)</code></p>',
  },
  'order': {
    'en': '<p>Specifies the order of the grid item.</p><p><code>&lt;integer&gt;</code></p>',
    'hi': '<p>????? ???? ?? ???? ????????? ???? ???</p><p><code>&lt;integer&gt;</code></p>',
    'lv': '<p>Norada "grid" elementu secibu.</p><p><code>&lt;integer&gt;</code></p>',
    'ro': '<p>Specifica ordinea elementului în grid.</p><p><code>&lt;integer&gt;</code></p>',
    'zh-cn': '<p>???????????</p><p><code>&lt;integer&gt;</code></p>',
    'zh-tw': '<p>???????????</p><p><code>&lt;integer&gt;</code></p>',
    'tr': '<p>Grid\'teki bir parçanin sirasini belirler.</p><p><code>&lt;integer&gt;</code></p>',
    'az': '<p>Grid\'d?ki bir hiss?nin sirasini t?yin ed?r.</p><p><code>&lt;integer&gt;</code></p>',
    'fr': '<p>Définit l\'ordre de l\'élément dans la grille.</p><p><code>&lt;integer&gt;</code></p>',
    'de': '<p>Bestimmt die Reihenfolge der Rasterelemente.</p><p><code>&lt;integer&gt;</code></p>',
    'nl': '<p>Bepaalt de volgorde van het griditem.</p><p><code>&lt;integer&gt;</code></p>',
    'pt-br': '<p>Especifica a ordem do item na grade.</p><p><code>&lt;integer&gt;</code></p>',
    'ru': '<p>?????????? ??????? grid-????????.</p><p><code>&lt;integer&gt;</code></p>',
    'pl': '<p>Definiuje kolejnosc elementu grid.</p><p><code>&lt;integer&gt;</code></p>',
    'es': '<p>Define el orden del elemento de la cuadrícula.</p><p><code>&lt;integer&gt;</code></p>',
    'sv': '<p>Specifierar ett grid elements sorteringsorder.</p><p><code>&lt;integer&gt;</code></p>',
    'fa': '<p>????? ???? ??? ???? ?? ???? ?? ???.</p><p><code>&lt;integer&gt;</code></p>',
    'it': '<p>Specifica l\'ordine degli elementi della griglia.</p><p><code>&lt;integer&gt;</code></p>',
    'ko': '<p>??? ??? ??? ?????.</p><p><code>&lt;integer&gt;</code></p>',
    'el': '<p>???sd?????e? t?? se??? t?? a?t??e?µ???? st? p???µa.</p><p><code>&lt;integer&gt;</code></p>',
    'ja': '<p>??????????????????</p><p><code>&lt;integer&gt;</code></p>',
    'ua': '<p>???????? ??????? grid ????????.</p><p><code>&lt;integer&gt;</code></p>',
    'no': '<p>Spesifiserer rekkefølgen til gridelementet.</p><p><code>&lt;integer&gt;</code></p>',
    'pt-pt': '<p>Especifica a ordem do elemento da grelha.</p><p><code>&lt;integer&gt;</code></p>',
    'bg': '<p>???????? ?????????? ?? grid-????????.</p><p><code>&lt;integer&gt;</code></p>',
    'he': '<p>???? ?? ???? ?? ?grid-item.</p><p><code>&lt;integer&gt;</code></p>',
    'ca': '<p>Defineix l\'ordre de l\'element de la quadrícula.</p><p><code>&lt;integer&gt;</code></p>',
    'vi': '<p>Xác d?nh th? t? c?a d?i tu?ng bên trong grid.</p><p><code>&lt;integer&gt;</code></p>',
    'ar': '<p>???? ????? ?????? ?? ??????.</p><p dir="ltr"><code>&lt;integer&gt;</code></p>',
    'fi': '<p>Määrittää ruudukkoelementin järjestyksen.</p><p><code>&lt;kokonaisluku&gt;</code></p>',
    'hu': '<p>Meghatározza a rácselem sorrendjét.</p><p><code>&lt;integer&gt;</code></p>',
    'id': '<p>Menentukan urutan dari item grid.</p><p><code>&lt;integer&gt;</code></p>',
    'tl': '<p>Tumutukoy ito sa order ng grid item.</p><p><code>&lt;integer&gt;</code></p>',
    'al': '<p>Specifikon rregullin e një grid item.</p><p><code>&lt;integer&gt;</code></p>',
    'et': '<p>Määrab ruudustiku üksuse järjestuse.</p><p><code>&lt;integer&gt;</code></p>',
    'th': '<p>????????????????? grid item</p><p><code>&lt;????????????&gt;</code></p>',
    'yo': '<p>S? pàtó à?? (order) èròjà grid item náà.</p><p><code>&lt;integer&gt;</code></p>',
    'sk': '<p>Urcuje poradie položky mriežky.</p><p><code>&lt;integer&gt;</code></p>',
    'ta': '<p>?????? ???????????? ????????? ?????????????.</p><p><code>&lt;integer&gt;</code></p>',
  },
};